import {readFile} from 'node:fs/promises';
import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {transformWithEsbuild} from 'vite';
const text = await readFile(new URL('../src/PolicyCard.jsx', import.meta.url), 'utf8');
const {code} = await transformWithEsbuild(text, 'PolicyCard.jsx', {jsx:'transform', jsxFactory:'React.createElement', format:'cjs'});
const mod = {exports:{}};
new Function('module','React',code)(mod,React);
const Card = mod.exports.default;
const render = props => renderToStaticMarkup(React.createElement(Card,props));
const row = {seq:1,target:'local',attempt:0,stage:'patch',decision:'BLOCK',complete:true,rule_id:'P-003',title:'모델 삭제',remedy:'모델 보존',version:'2.2.0',reason_code:'prisma_structure_changed',path:'prisma/schema.prisma'};
test('missing results never imply success',()=>{assert.match(render({}),/아직 기록된/); assert.doesNotMatch(render({}),/policy-pass/);});
test('failure shows rule, evidence and remedy',()=>{const html=render({data:{results:[row]}});for(const term of ['차단','P-003','prisma/schema.prisma','모델 보존']) assert.ok(html.includes(term));});
test('retry and targets remain distinct',()=>{const html=render({data:{results:[row,{...row,seq:2,target:'aws',attempt:1,decision:'PASS'}]}});for(const term of ['LOCAL','AWS','최초 검사','재시도']) assert.ok(html.includes(term));});
test('unsupported and error are separate from blocked',()=>{const html=render({data:{results:[{...row,decision:'UNSUPPORTED',complete:false},{...row,seq:2,decision:'ERROR'}]}});assert.match(html,/미지원/);assert.match(html,/검사 오류/);assert.match(html,/검사 미완료/);});
test('source-controlled text is escaped',()=>{const html=render({data:{results:[{...row,path:'<img src=x onerror=alert(1)>',title:'<script>bad</script>'}]}});assert.doesNotMatch(html,/<script>|<img/);assert.match(html,/&lt;script/);});
test('failed refresh does not render stale success',()=>{const html=render({error:true,data:{results:[{...row,decision:'PASS'}]}});assert.match(html,/불러오지 못/);assert.doesNotMatch(html,/policy-pass/);});
